# Generated by Django 2.2 on 2019-04-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0002_auto_20190429_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default=23,
                                   help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>',
                                   max_length=13, verbose_name='ISBN'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(help_text='Enter a brief description of the book', max_length=1000),
        ),
    ]
